2022-04-08 21:53:01,969 - [ERROR] - __main__ - (main.py).connecting(245) - 'ModbusIOException' object has no attribute 'registers'
Traceback (most recent call last):
  File "E:\Python\Projects\BempIO\main.py", line 239, in connecting
    num1 = str(client.read_holding_registers(0x010C, unit=self.address).registers[0])
AttributeError: 'ModbusIOException' object has no attribute 'registers'
2022-04-08 21:54:01,550 - [ERROR] - __main__ - (main.py).connecting(244) - 'ModbusIOException' object has no attribute 'registers'
Traceback (most recent call last):
  File "E:\Python\Projects\BempIO\main.py", line 238, in connecting
    num1 = str(client.read_holding_registers(0x010C, 1, unit=self.address).registers[0])
AttributeError: 'ModbusIOException' object has no attribute 'registers'
