2022-04-08 12:11:41,572 - [ERROR] - __main__ - (main.py).get_dio_01_address(305) - invalid literal for int() with base 16: '0x'
Traceback (most recent call last):
  File "C:/Python Projects/BempIO/main.py", line 298, in get_dio_01_address
    assert isinstance(int(di_01_address, 16), int), "Неправильный адрес DI 1"
ValueError: invalid literal for int() with base 16: '0x'
